update
upgrade --all

cask
tap homebrew/versions

# Install more recent versions of some OS X tools.
install vim --override-system-vi
install homebrew/dupes/grep
install homebrew/dupes/openssh
install homebrew/dupes/screen

# Install other useful binaries.
install silver-searcher
install git
install hub
install tree
install watchman

# Programming
cask install iterm2
install neovim/neovim/neovim

# General
cask install dropbox
cask install chrome
cask install things
cask install dockertoolbox
cask install spectacle
cask install fantastical
cask install recordit
cask install slack
cask install sketch
cask install dash
cask install evernote

# Remove outdated versions from the cellar.
cleanup
